### ISSUE TITLE
Wrong total order value on shops with different base currency (multiple currencies)

### ISSUE THREAD

**Issue by printminion** [liqpay/plugin-magento#10]
Fixed in pull request https://github.com/liqpay/plugin-magento/pull/9

Currently liqpay/plugin-magento is sending wrong total order value via liqpay api.
It happens if you have magento shop with multiple currencies (base currency != payment currency)

IS:
$amount = $order->getBaseGrandTotal(); //6 <------- UAH value is expected
$currency = $order->getOrderCurrencyCode(); //UAH

Must be:
$amount = $order->getGrandTotal(); //155.0400
$currency = $order->getOrderCurrencyCode(); //UAH

or
$amount = $order->getBaseGrandTotal(); //6.0000
$currency = $order->getBaseCurrencyCode(); //USD

**Comment by viplifes** [comment]
Thanks!
