### ISSUE TITLE
Fatal error: Class 'LiqPay' not found in /home/olympnik/public_html/app/code/LiqpayMagento/LiqPay/Sdk/LiqPay.php on line 15

### ISSUE THREAD

**Issue by marina58** [liqpay/plugin-magento#19]
Доброго времени суток. 
Установлена Magento 2.1.7. , LiqPay 3.0. 
В бекэнде LiqPay появился. В config.php модуль появился. В базе данных запись о модуле появилась. 
Кеш почищен.
При чекауте из корзины выдает ошибку 
Good time of the day.
Magento 2.1.7 is installed. , LiqPay 3.0.
In the backend, LiqPay appeared. The config.php module has appeared. In the database, the entry for the module appeared.
The cache is cleaned.
When checking out of the basket gives an error
Fatal error: Class 'LiqPay' not found in /home/olympnik/public_html/app/code/LiqpayMagento/LiqPay/Sdk/LiqPay.php on line 15.
Подскажите пожалуста, что делать? Tell me please what to do?

**Comment by ivan-krechko** [comment]
Мушу Вас розчарувати... Згідно політики ПБ нічого хорошого Ви тут не почуєте... ))

**Comment by marina58** [comment]
Сама знайшла вирішення
