### ISSUE TITLE
Не приходит письмо клиенту при успешной оплате.

### ISSUE THREAD

**Issue by alexzabolotny** [liqpay/plugin-magento#2]
Файл `Liqpay/Liqpay/Model/PaymentMethod.php` строка 231, возможно пропущено `$order->sendNewOrderEmail();`.

Система:  Magento 1.9.0.0

**Comment by alexzabolotny** [comment]
Уже почти год прошел, есть ли какие-то новости?

**Comment by dpzz** [comment]
Доброго времени!
Отправка клиенту письма - это опция, она индивидуальна у каждого магазина, поэтому разработчики не предусматривали ее "по умолчанию". Кроме того, в самой системе Liqpay есть, например, возможность для клиента отправить себе чек самостоятельно.
