### ISSUE TITLE
После лсуществления оплаты не перенаправляет на страницу подтверждения

### ISSUE THREAD

**Issue by gonorovsky** [liqpay/plugin-magento#6]
Не перенаправляет на страницу MAGENTO после подтверждения проведения оплаты в liqpay

**Comment by isitnikov** [comment]
Возникают ли при этом какие-то эксепшены? Если да, приведите пожалуйста здесь.

**Comment by gonorovsky** [comment]
Что вы имеете ввиду под эксепшинами (конкретный лог или ещё что-то)? Но по
тестам при покупке (именно не сенд бокс, а реальная покупка) - проблема
есть. Причём, на двух разных версиях пробовали (190/192) на свежих
установках.

Чт, 8 жовт. 2015 14:03 Ihor Sytnykov <notifications@github.com> пише:

> Возникают ли при этом какие-то эксепшены? Если да, приведите пожалуйста
> здесь.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/liqpay/plugin-magento/issues/6#issuecomment-146505208>
> .
>
-- 
Regards,
Volodymyr Gonorovskyi
Managing Partner @ Gonorovsky Digital Investment
gonorovsky.com

Tel., Viber: +38 095 11 33 401
facebook.com/gonorovskyi

**Comment by isitnikov** [comment]
Я имею ввиду var/log/exception.log

**Comment by gonorovsky** [comment]
ничего нету. если ошибки по факту туда попадают то после тестовой покупки
там ничего нету.

On Thu, 8 Oct 2015 at 14:37 Ihor Sytnykov <notifications@github.com> wrote:

> Я имею ввиду var/log/exception.log
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/liqpay/plugin-magento/issues/6#issuecomment-146510882>
> .
>
-- 
Regards,
Volodymyr Gonorovskyi
Managing Partner @ Gonorovsky Digital Investment
gonorovsky.com

Tel., Viber: +38 095 11 33 401
facebook.com/gonorovskyi

**Comment by isitnikov** [comment]
Понял. Спасибо, разберусь сегодня.

**Comment by gonorovsky** [comment]
Также, не изменяеться статус заказа при успешной оплате ;(

Чт, 8 жовт. 2015 14:54 Ihor Sytnykov <notifications@github.com> пише:

> Понял. Спасибо, разберусь сегодня.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/liqpay/plugin-magento/issues/6#issuecomment-146515402>
> .
>
-- 
Regards,
Volodymyr Gonorovskyi
Managing Partner @ Gonorovsky Digital Investment
gonorovsky.com

Tel., Viber: +38 095 11 33 401
facebook.com/gonorovskyi

**Comment by gonorovsky** [comment]
есть новости по багу?

**Comment by dpzz** [comment]
Доброго времени!
Для того чтобы после проведения оплаты в Liqpay пользователь был переадресован на домашнюю страницу магазина, в настройках магазина https://www.liqpay.com/ru/admin/business/settings/api/ установите параметр "Авторедирект".

**Comment by gonorovsky** [comment]
Спасибо, но пишет: не передан параметр result_url

Чт, 19 лист. 2015 10:39 dpzz <notifications@github.com> пише:

> Доброго времени!
> Для того чтобы после проведения оплаты в Liqpay пользователь был
> переадресован на домашнюю страницу магазина, в настройках магазина
> https://www.liqpay.com/ru/admin/business/settings/api/ установите
> параметр "Авторедирект".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/liqpay/plugin-magento/issues/6#issuecomment-157989827>
> .
>
-- 
Regards,
Volodymyr Gonorovskyi
Managing Partner @ Gonorovsky Digital Investment
gonorovsky.com

Tel., Viber: +38 095 11 33 401
facebook.com/gonorovskyi

**Comment by dpzz** [comment]
https://github.com/liqpay/plugin-magento/blob/master/app/code/local/Liqpay/Liqpay/Model/PaymentMethod.php#L90
параметр result_url как вы можете убедиться есть в коде. 
Я бы рекомендовал все еще раз обновить, перезалить, и в конфиге самого модуля в админке Liqpay проверить настройки.
Если не работает релиз liq&buy3.0, попробуйте новый релиз checkout3.0
https://github.com/liqpay/plugin-magento/tree/liq%26buy3.0
https://github.com/liqpay/plugin-magento/tree/checkout3.0

**Comment by gonorovsky** [comment]
какая разница между этими версиями?
Обновил, но не обратил внимание на кукую из версий (как посмотреть?).
Сейчас у меня все работает, а после совершения покупки появилась кнопка
"вернуться в магазин". При нажатии - возвращает на страницу успешной
покупки. Спасибо!

Но в настройках по прежнему пишет "не передан параметр result_url" при
выборе авторедиректа.

On Fri, 20 Nov 2015 at 12:32 dpzz <notifications@github.com> wrote:

> Reopened #6 <https://github.com/liqpay/plugin-magento/issues/6>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/liqpay/plugin-magento/issues/6#event-470228511>.
>
-- 
Regards,
Volodymyr Gonorovskyi
Managing Partner @ Gonorovsky Digital Investment
gonorovsky.com

Tel., Viber: +38 095 11 33 401
facebook.com/gonorovskyi

**Comment by gonorovsky** [comment]
разницу вижу.

On Fri, 20 Nov 2015 at 12:40 Volodymyr Gonorovskyi <
volodymyr.gonorovskyi@gmail.com> wrote:

> какая разница между этими версиями?
> Обновил, но не обратил внимание на кукую из версий (как посмотреть?).
> Сейчас у меня все работает, а после совершения покупки появилась кнопка
> "вернуться в магазин". При нажатии - возвращает на страницу успешной
> покупки. Спасибо!
>
> Но в настройках по прежнему пишет "не передан параметр result_url" при
> выборе авторедиректа.
>
> On Fri, 20 Nov 2015 at 12:32 dpzz <notifications@github.com> wrote:
>
>> Reopened #6 <https://github.com/liqpay/plugin-magento/issues/6>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/liqpay/plugin-magento/issues/6#event-470228511>.
>>
> --
> Regards,
> Volodymyr Gonorovskyi
> Managing Partner @ Gonorovsky Digital Investment
> gonorovsky.com
>
> Tel., Viber: +38 095 11 33 401
> facebook.com/gonorovskyi
>
-- 
Regards,
Volodymyr Gonorovskyi
Managing Partner @ Gonorovsky Digital Investment
gonorovsky.com

Tel., Viber: +38 095 11 33 401
facebook.com/gonorovskyi

**Comment by dpzz** [comment]
В админке магазина вы можете заполнить этот параметр, тогда флаги "Авторедирект" и "POST..." успешно сохранятся.
"URL магазина клиент-сервер:"

Но поскольку в плагине указывается явно result_url, то он и будет использован. Если же его в плагине убрать, то тогда подставится result_url, указанный в админке "URL магазина клиент-сервер:"

**Comment by gonorovsky** [comment]
Спасибо. Разобрался

Пт, 20 лист. 2015 12:52 dpzz <notifications@github.com> пише:

> В админке магазина вы можете заполнить этот параметр, тогда флаги
> "Авторедирект" и "POST..." успешно сохранятся.
> "URL магазина клиент-сервер:"
>
> Но поскольку в плагине указывается явно result_url, то он и будет
> использован. Если же его в плагине убрать, то тогда подставится result_url,
> указанный в админке "URL магазина клиент-сервер:"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/liqpay/plugin-magento/issues/6#issuecomment-158357420>
> .
>
-- 
Regards,
Volodymyr Gonorovskyi
Managing Partner @ Gonorovsky Digital Investment
gonorovsky.com

Tel., Viber: +38 095 11 33 401
facebook.com/gonorovskyi
