### ISSUE TITLE
Что нужно указать в "URL уведомлений сервер-сервер" в админке LiqPay 

### ISSUE THREAD

**Issue by estupnikov** [liqpay/plugin-magento#8]
Что нужно указать в "URL уведомлений сервер-сервер" в админке LiqPay, чтоб получать уведомления об успешно проведенной оплате и апдейтить статус заказа?
Или этих функций не предусмотрено плагином?

**Comment by dpzz** [comment]
Доброго времени!
В обновлении уже содержатся все необходимые параметры, в админке можете ничего не указывать.

**Comment by estupnikov** [comment]
Добрый день.

Обновил плагин, обновил кеш. После проведения оплаты заказ по прежнему обозначен в магазине как "Новый".

**Comment by dpzz** [comment]
Доброго времени!
Нужно убедиться что вы получаете ответ от сервера Liqpay, проще всего залогировать его.
Какой релиз используется? checkout3.0 или liq&but3.0?
